# Generated by Django 5.1.2 on 2025-09-17 15:04

import webnotify.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webnotify', '0002_monitoredurl_css_selector_alter_monitoredurl_user_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', webnotify.models.UserManager()),
            ],
        ),
    ]
