# Generated by Django 5.2.6 on 2025-09-18 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webnotify', '0004_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='api_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_ringtone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webnotify.customringtone'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='volume',
            field=models.PositiveIntegerField(default=80),
        ),
    ]
